[global]

workgroup = NORTHWIND

server string = Northwind File Server

netbios name = NW-FILE01

security = user

map to guest = Bad User

server role = standalone server

disable netbios = no


[public]

path = /shares/public

browseable = yes

read only = yes

guest ok = yes

force user = nobody
